buildscript {
    val jetifierVersion = "1.0.0-beta10"
    val hiltGradlePluginVersion = "2.60.1"
    val googleServicesPluginVersion = "4.5.0"
    val firebaseCrashlyticsPluginVersion = "3.0.7"
    val bugsnagGradlePluginVersion = "8.+"

    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
        maven { url = uri("https://maven.sumsub.com/repository/maven-public/") }
    }
    dependencies {
        classpath("com.android.tools.build.jetifier:jetifier-processor:$jetifierVersion")
        classpath("com.google.dagger:hilt-android-gradle-plugin:$hiltGradlePluginVersion")
        classpath("com.google.gms:google-services:$googleServicesPluginVersion")
        classpath("com.google.firebase:firebase-crashlytics-gradle:$firebaseCrashlyticsPluginVersion")
        classpath("com.bugsnag:bugsnag-android-gradle-plugin:$bugsnagGradlePluginVersion")
    }
}

plugins {
<<<<<<< HEAD
    id("com.android.application") version "9.3.0" apply false
    id("com.android.library") version "9.3.0" apply false
    id("org.jetbrains.kotlin.plugin.parcelize") version "2.4.10" apply false
    id("de.undercouch.download") version "5.5.0" apply false
    id("com.google.android.libraries.mapsplatform.secrets-gradle-plugin") version "2.0.1" apply false
    id("org.jetbrains.kotlin.plugin.serialization") version "2.4.10" apply false
    id("com.google.devtools.ksp") version "2.3.10" apply false
    id("androidx.room3") version "3.0.0" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.4.10" apply false
    id("org.jetbrains.kotlin.jvm") version "2.4.0" apply false
    id("com.google.firebase.firebase-perf") version "2.0.2" apply false
}

val bitcoinVersion by extra("0.17.1")
val fragmentVersion by extra("1.8.9")
val activity_version by extra("1.13.0")
val lifecycleVersion by extra("2.10.0")
val appcompatVersion by extra("1.7.1")
val pagingVersion by extra("3.5.0")
val coilVersion by extra("3.5.0")
val collectionx by extra("1.6.0")
val roomVersion by extra("3.0.0")
val sqliteVersion by extra("2.7.0")
val navigationVersion by extra("2.9.8")
val workManagerVersion by extra("2.11.2")
val constraintLayoutVersion by extra("2.2.1")
val constraintLayoutComposeVersion by extra("1.1.1")
val supportLibVersion by extra("1.0.0")
val recyclerViewVersion by extra("1.4.0")
val browserVersion by extra("1.10.0")
val biometricVersion by extra("1.4.0-alpha07")
val mdcVersion by extra("1.14.0")
val exifinterfaceVersion by extra("1.4.2")
val preferenceVersion by extra("1.2.1")
val hiltVersion by extra("2.59.2")
val hiltAndroidxVersion by extra("1.3.0")
val androidxVersion by extra("1.18.0")
val viewpagerVersion by extra("1.1.0")
val sharetargetVersion by extra("1.2.0")
val coordinatorVersion by extra("1.3.0")
val espressoVersion by extra("3.7.0")
val cameraxVersion by extra("1.6.1")
val glideVersion by extra("5.0.7")
val timberVersion by extra("5.0.1")
val okhttpVersion by extra("5.4.0")
val rxJavaVersion by extra("2.2.21")
val rxAndroidVersion by extra("2.1.1")
val rxbindingVersion by extra("3.1.0")
val retrofitVersion by extra("3.0.0")
val coroutineAdapterVersion by extra("0.9.2")
val loggerVersion by extra("2.2.0")
val kotlinVersion by extra("2.3.21")
val libphonenumberVersion by extra("9.0.30")
val coroutinesVersion by extra("1.11.0")
val firebaseVersion by extra("18.0.2")
val firebaseMessageVersion by extra("21.0.1")
val firebaseDylinkVersion by extra("19.1.1")
val firebaseMLVersion by extra("24.0.3")
val mlkitBarcodeVersion by extra("17.3.0")
val jwtVersion by extra("0.9.1")
val zxingVersion by extra("3.5.4")
val rxpermissionsVersion by extra("0.10.3")
val ucropVersion by extra("2.2.11")
val glideTransformationsVersion by extra("4.3.0")
val jobqueueVersion by extra("3.1.0")
val stickyheadersrecyclerviewVersion by extra("0.7")
val threetenabpVersion by extra("1.4.9")
val signalVersion by extra("2.8.1")
val fabVersion by extra("1.6")
val playVersion by extra("2.1.0")
val googlePlayServicesVersion by extra("18.1.1")
val svgVersion by extra("1.4")
val reboundVersion by extra("0.3.8")
val shimmerVersion by extra("0.5.0")
val composeShimmerVersion by extra("1.4.0")
val media3Version by extra("1.10.1")
val perfVersion by extra("19.0.10")
val markwonVersion by extra("4.6.2")
val prism4jVersion by extra("2.0.0")
val swirlVersion by extra("1.3.0")
val indicatorseekbarVersion by extra("2.1.2")
val emojiVerison by extra("1.6.0")
val cronetOkhttpVersion by extra("0.1.1")
val diffUtilsVersion by extra("4.16")
val argon2ktVersion by extra("0.0.2")
val keccakVersion by extra("1.1.3")
val streetMapVersion by extra("6.1.20")
val junitVersion by extra("4.13.2")
val testCoreVersion by extra("1.7.0")
val mockitoVersion by extra("1.10.19")
val androidxJunitVersion by extra("1.3.0")
val hamcrestVersion by extra("1.3")
val mockitoCoreVersion by extra("2.7.19")
val testSupVersion by extra("1.0.1")
val robolectricVersion by extra("4.16.1")
val gsonVersion by extra("2.14.0")
val serializationVersion by extra("1.11.0")
val autodisposeVersion by extra("1.4.1")
val jsoupVersion by extra("1.13.1")
val isoparserVersion by extra("1.0.6")
val largeImageViewVersion by extra("1.1.1")
val webrtcVersion by extra("1.0.30039")
val bitcoinPaymentURI by extra("1.0.3")
val startupVersion by extra("1.2.0")
val dnsVersion by extra("2.1.9")
val appCenterSdkVersion by extra("4.3.1")
val audioSwitchVersion by extra("1.1.8")
val balloonVersion by extra("1.7.6")
val markdownVersion by extra("0.7.3")
val bcVersion by extra("1.70")
val jsonVersion by extra("20251224")
val composeVersion by extra("1.11.2")
val accompanistVersion by extra("0.36.0")
val web3jVersion by extra("4.8.7-android")
val sol4kVersion by extra("0.7.0")
val sumsubVersion by extra("1.44.1")
val checkoutFramesVersion by extra("4.2.3")
val checkoutSecureVersion by extra("3.2.6")
val checkoutRiskVersion by extra("1.0.6")
val playWalletVersion by extra("20.0.0")
val playPayVersion by extra("16.5.0")
val datastoreVersion by extra("1.2.1")
val protobufVersion by extra("3.11.0")
val appsFlyerVersion by extra("6.18.0")
val installreferrerVersion by extra("2.2")
val billingVersion by extra("8.3.0")
val lottieComposeVersion by extra("6.7.1")
val composeBomVersion by extra("2026.05.01")
val activityComposeVersion by extra("1.13.0")
val reownBomVersion by extra("1.6.13")
val kotsonVersion by extra("2.5.0")
val playServicesMapsVersion by extra("20.0.0")
val playServicesLocationVersion by extra("21.3.0")
val firebaseBomVersion by extra("34.13.0")
val billingKtxVersion by extra("8.3.0")
val webpdecoderVersion by extra("2.7.4.16.0")
val tweetnaclVersion by extra("0.1.6")
val sol4kUtilitiesVersion by extra("0.1.0")
val desugarJdkLibsVersion by extra("2.1.5")
val bugsnagVersion by extra("6.26.0")
=======
    id("com.android.application") apply false
    id("com.android.library") apply false
    id("org.jetbrains.kotlin.plugin.parcelize") apply false
    id("de.undercouch.download") apply false
    id("com.google.android.libraries.mapsplatform.secrets-gradle-plugin") apply false
    id("org.jetbrains.kotlin.plugin.serialization") apply false
    id("com.google.devtools.ksp") apply false
    id("org.jetbrains.kotlin.plugin.compose") apply false
    id("com.google.firebase.firebase-perf") apply false
}


extra.set("androidNdkVersion", "27.0.12077973")
extra.set("jetifierVersion", "1.0.0-beta10")
extra.set("kotlinVersion", "2.4.10")
extra.set("tinkVersion", "0.0.13")
extra.set("securityCryptoVersion", "1.1.0")
extra.set("webkitVersion", "1.16.0")
extra.set("mixinJwtVersion", "2b1c61aa2f")
extra.set("alphabetIndexVersion", "1.0.95")
extra.set("web3jVersion", "4.12.3-android")
extra.set("entityExtractionVersion", "16.0.0-beta6")
extra.set("bitcoinVersion", "0.17.1")
extra.set("fragmentVersion", "1.8.9")
extra.set("activityVersion", "1.13.0")
extra.set("lifecycleVersion", "2.11.0")
extra.set("appcompatVersion", "1.7.1")
extra.set("pagingVersion", "3.5.0")
extra.set("coilVersion", "3.5.0")
extra.set("collectionVersion", "1.6.0")
extra.set("roomVersion", "2.8.4")
extra.set("navigationVersion", "2.9.8")
extra.set("workManagerVersion", "2.11.2")
extra.set("constraintLayoutVersion", "2.2.1")
extra.set("constraintLayoutComposeVersion", "1.1.1")
extra.set("supportLibVersion", "1.0.0")
extra.set("recyclerViewVersion", "1.4.0")
extra.set("browserVersion", "1.10.0")
extra.set("biometricVersion", "1.4.0-alpha07")
extra.set("mdcVersion", "1.14.0")
extra.set("exifinterfaceVersion", "1.4.2")
extra.set("preferenceVersion", "1.2.1")
extra.set("hiltVersion", "2.60.1")
extra.set("hiltAndroidxVersion", "1.4.0")
extra.set("androidxVersion", "1.19.0")
extra.set("viewpagerVersion", "1.1.0")
extra.set("sharetargetVersion", "1.2.0")
extra.set("coordinatorVersion", "1.3.0")
extra.set("espressoVersion", "3.7.0")
extra.set("cameraxVersion", "1.6.1")
extra.set("glideVersion", "5.0.9")
extra.set("timberVersion", "5.0.1")
extra.set("okhttpVersion", "5.4.0")
extra.set("rxJavaVersion", "2.2.21")
extra.set("rxAndroidVersion", "2.1.1")
extra.set("rxbindingVersion", "3.1.0")
extra.set("retrofitVersion", "3.0.0")
extra.set("coroutineAdapterVersion", "0.9.2")
extra.set("libphonenumberVersion", "9.0.30")
extra.set("coroutinesVersion", "1.11.0")
extra.set("mlkitBarcodeVersion", "17.3.0")
extra.set("zxingVersion", "3.5.4")
extra.set("ucropVersion", "2.2.11")
extra.set("glideTransformationsVersion", "4.3.0")
extra.set("jobqueueVersion", "3.1.0")
extra.set("stickyHeadersRecyclerViewVersion", "0.7")
extra.set("threetenabpVersion", "1.4.9")
extra.set("signalVersion", "2.8.1")
extra.set("playVersion", "2.1.0")
extra.set("googlePlayServicesVersion", "18.1.1")
extra.set("svgVersion", "1.4")
extra.set("reboundVersion", "0.3.8")
extra.set("shimmerVersion", "0.5.0")
extra.set("composeShimmerVersion", "1.4.0")
extra.set("media3Version", "1.10.1")
extra.set("markwonVersion", "4.6.2")
extra.set("prism4jVersion", "2.0.0")
extra.set("swirlVersion", "1.3.0")
extra.set("indicatorseekbarVersion", "2.1.2")
extra.set("emojiVersion", "1.6.0")
extra.set("cronetOkhttpVersion", "0.1.1")
extra.set("diffUtilsVersion", "4.16")
extra.set("argon2ktVersion", "0.0.2")
extra.set("keccakVersion", "1.1.3")
extra.set("streetMapVersion", "6.1.20")
extra.set("junitVersion", "4.13.2")
extra.set("testCoreVersion", "1.7.0")
extra.set("mockitoVersion", "1.10.19")
extra.set("androidxJunitVersion", "1.3.0")
extra.set("robolectricVersion", "4.16.1")
extra.set("gsonVersion", "2.14.0")
extra.set("serializationVersion", "1.11.0")
extra.set("autodisposeVersion", "1.4.1")
extra.set("bitcoinPaymentUriVersion", "1.0.3")
extra.set("startupVersion", "1.2.0")
extra.set("dnsVersion", "2.1.9")
extra.set("audioSwitchVersion", "1.1.8")
extra.set("balloonVersion", "1.7.6")
extra.set("markdownVersion", "0.7.3")
extra.set("bcVersion", "1.70")
extra.set("jsonVersion", "20251224")
extra.set("composeVersion", "1.11.4")
extra.set("accompanistVersion", "0.36.0")
extra.set("sol4kVersion", "0.8.2")
extra.set("protobufVersion", "3.11.0")
extra.set("kotsonVersion", "2.5.0")
extra.set("lottieComposeVersion", "6.7.1")
extra.set("composeBomVersion", "2026.06.01")
extra.set("reownBomVersion", "1.6.13")
extra.set("playServicesMapsVersion", "20.0.0")
extra.set("playServicesLocationVersion", "21.3.0")
extra.set("firebaseBomVersion", "34.13.0")
extra.set("webpDecoderVersion", "2.7.4.16.0")
extra.set("tweetnaclVersion", "0.1.6")
extra.set("sol4kUtilitiesVersion", "0.1.0")
extra.set("desugarJdkLibsVersion", "2.1.5")
extra.set("bugsnagVersion", "6.26.0")
extra.set("sumsubVersion", "1.44.1")
extra.set("checkoutFramesVersion", "4.2.3")
extra.set("checkoutSecureVersion", "3.2.6")
extra.set("checkoutRiskVersion", "1.0.6")
extra.set("playWalletVersion", "20.0.0")
extra.set("playPayVersion", "16.5.0")
extra.set("datastoreVersion", "1.2.1")
extra.set("appsFlyerVersion", "6.18.0")
extra.set("installReferrerVersion", "2.2")
extra.set("billingVersion", "8.3.0")
>>>>>>> origin/master

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
        maven { url = uri("https://maven.sumsub.com/repository/maven-public/") }
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
            name = "OSS-Sonatype"
        }
        maven { url = uri("https://artifacts.consensys.net/public/maven/maven/") }
        maven { url = uri("https://maven.fpregistry.io/releases") }
        maven {
            url = uri("https://maven.pkg.github.com/checkout/checkout-3ds-sdk-android")
            credentials {
                username = project.findProperty("GITHUB_ID") as String? ?: System.getenv("GITHUB_ID") ?: ""
                password = project.findProperty("GITHUB_PACKAGES_TOKEN") as String? ?: System.getenv("GITHUB_PACKAGES_TOKEN") ?: ""
            }
        }
    }
}
