/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package supranational.blst;

public class P2_Affine {
  private transient long[] swigCPtr;

  protected P2_Affine(long[] cPtr) { swigCPtr = cPtr; }

  protected static long[] getCPtr(P2_Affine obj) {
    return obj != null ? obj.swigCPtr : null;
  }

  public P2_Affine dup() { return new P2_Affine(swigCPtr.clone()); }

  public P2_Affine() { this(blstJNI.new_P2_Affine__SWIG_0()); }

  public P2_Affine(byte[] in) { this(blstJNI.new_P2_Affine__SWIG_1(in)); }

  public P2_Affine(P2 jacobian) { this(blstJNI.new_P2_Affine__SWIG_2(P2.getCPtr(jacobian))); }

  public P2 to_jacobian() {
    return new P2(blstJNI.P2_Affine_to_jacobian(swigCPtr));
}

  public byte[] serialize() { return blstJNI.P2_Affine_serialize(swigCPtr); }

  public byte[] compress() { return blstJNI.P2_Affine_compress(swigCPtr); }

  public boolean on_curve() {
    return blstJNI.P2_Affine_on_curve(swigCPtr);
  }

  public boolean in_group() {
    return blstJNI.P2_Affine_in_group(swigCPtr);
  }

  public boolean is_inf() {
    return blstJNI.P2_Affine_is_inf(swigCPtr);
  }

  public boolean is_equal(P2_Affine p) {
    return blstJNI.P2_Affine_is_equal(swigCPtr, P2_Affine.getCPtr(p));
  }

  public BLST_ERROR core_verify(P1_Affine pk, boolean hash_or_encode, byte[] msg, String DST, byte[] aug) {
    return BLST_ERROR.swigToEnum(blstJNI.P2_Affine_core_verify__SWIG_0(swigCPtr, P1_Affine.getCPtr(pk), hash_or_encode, msg, DST, aug));
  }

  public BLST_ERROR core_verify(P1_Affine pk, boolean hash_or_encode, byte[] msg, String DST) {
    return BLST_ERROR.swigToEnum(blstJNI.P2_Affine_core_verify__SWIG_2(swigCPtr, P1_Affine.getCPtr(pk), hash_or_encode, msg, DST));
  }

  public BLST_ERROR core_verify(P1_Affine pk, boolean hash_or_encode, byte[] msg) {
    return BLST_ERROR.swigToEnum(blstJNI.P2_Affine_core_verify__SWIG_3(swigCPtr, P1_Affine.getCPtr(pk), hash_or_encode, msg));
  }

  public static P2_Affine generator() {
    return new P2_Affine(blstJNI.P2_Affine_generator());
}

}
