package one.mixin.android.db.contants

const val IMAGES = "'SIGNAL_IMAGE', 'PLAIN_IMAGE', 'ENCRYPTED_IMAGE'"
const val VIDEOS = "'SIGNAL_VIDEO', 'PLAIN_VIDEO', 'ENCRYPTED_VIDEO'"
const val AUDIOS = "'SIGNAL_AUDIO', 'PLAIN_AUDIO', 'ENCRYPTED_AUDIO'"
const val DATA = "'SIGNAL_DATA', 'PLAIN_DATA', 'ENCRYPTED_DATA'"
const val LIVES = "'SIGNAL_LIVE', 'PLAIN_LIVE', 'ENCRYPTED_LIVE'"
const val TRANSCRIPTS = "'SIGNAL_TRANSCRIPT', 'PLAIN_TRANSCRIPT', 'ENCRYPTED_TRANSCRIPT'"