name: Android CI

on:
  push:
    branches:
    - master
    - bugfix/*
    - feature/*
  pull_request_target:
    branches: [ master ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Set google-service.json data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo "$DATA" > app/src/debug/google-services.json

    - name: Build
      run: ./gradlew clean assembleDebug --stacktrace

    - name: Run tests
      run: ./gradlew testGooglePlayDebugUnitTest